# Generated by Django 3.1.7 on 2021-04-14 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='answered',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='question',
            name='count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
