# Generated by Django 3.1.7 on 2021-04-14 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelapi', '0003_question_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='count',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
